/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.junit.Test;

import static org.example.ChessBoard.setup_board;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void moveGenAndSearchTest() {

        setup_board("rnb1kbnr/pppp1qpp/8/4p3/8/4P3/PPPP1PPP/RNB1KBNR w KQkq -");
        Eval.init_tables();
        int score = Search.search(6, 0);

        assertEquals(-1010, score);

        String pv = Search.get_pv();
        System.out.println(pv);

        assertTrue(pv.equals("b1c3  e8d8  f1d3  d7d5  e1d1  f7f2  \n"));
    }
}
